/**
 * Panel traceability manifest — generated from MARKET_PANELS.
 * Run: node scripts/gen-panel-manifest.mjs
 * Prefer extracting UI into markets/<m>/panels/ (see src/panels/README.md).
 */

/** @typedef {{ marketId: string, panelId: string, title: string, key: string, dashboard: string, module: string|null, placeholders: string }} PanelManifestEntry */

/** @type {PanelManifestEntry[]} */
export const PANEL_MANIFEST = [
  {
    key: "equities:kpi",
    marketId: "equities",
    panelId: "kpi",
    title: "Key Indices",
    dashboard: "src/markets/equities/EquitiesMarket.jsx",
    module: "src/panels/equities/kpi.jsx",
    placeholders: "equities:kpi",
  },
  {
    key: "equities:heatmap",
    marketId: "equities",
    panelId: "heatmap",
    title: "Equity Heatmap",
    dashboard: "src/markets/equities/EquitiesMarket.jsx",
    module: "src/panels/equities/heatmap.jsx",
    placeholders: "equities:heatmap",
  },
  {
    key: "equities:sidebar",
    marketId: "equities",
    panelId: "sidebar",
    title: "Market Summary",
    dashboard: "src/markets/equities/EquitiesMarket.jsx",
    module: "src/panels/equities/sidebar.jsx",
    placeholders: "equities:sidebar",
  },
  {
    key: "equities:portfolio",
    marketId: "equities",
    panelId: "portfolio",
    title: "Portfolio Tracker",
    dashboard: "src/markets/equities/EquitiesMarket.jsx",
    module: "src/panels/equities/portfolio.jsx",
    placeholders: "equities:portfolio",
  },
  {
    key: "equities:universe-updates",
    marketId: "equities",
    panelId: "universe-updates",
    title: "Universe Expansion Queue",
    dashboard: "src/markets/equities/EquitiesMarket.jsx",
    module: "src/panels/equities/universe-updates.jsx",
    placeholders: "equities:universe-updates",
  },
  {
    key: "equities:sec-fundamentals",
    marketId: "equities",
    panelId: "sec-fundamentals",
    title: "SEC Fundamentals",
    dashboard: "src/markets/equities/EquitiesMarket.jsx",
    module: "src/panels/equities/sec-fundamentals.jsx",
    placeholders: "equities:sec-fundamentals",
  },
  {
    key: "equities:sec-filings",
    marketId: "equities",
    panelId: "sec-filings",
    title: "SEC Filing Activity",
    dashboard: "src/markets/equities/EquitiesMarket.jsx",
    module: "src/panels/equities/sec-filings.jsx",
    placeholders: "equities:sec-filings",
  },
  {
    key: "equities:bea-corporate-profits",
    marketId: "equities",
    panelId: "bea-corporate-profits",
    title: "BEA Corporate Profits",
    dashboard: "src/markets/equities/EquitiesMarket.jsx",
    module: "src/panels/equities/bea-corporate-profits.jsx",
    placeholders: "equities:bea-corporate-profits",
  },
  {
    key: "equities:wb-market-cap",
    marketId: "equities",
    panelId: "wb-market-cap",
    title: "World Bank Market Cap",
    dashboard: "src/markets/equities/EquitiesMarket.jsx",
    module: "src/panels/equities/wb-market-cap.jsx",
    placeholders: "equities:wb-market-cap",
  },
  {
    key: "bonds:kpi",
    marketId: "bonds",
    panelId: "kpi",
    title: "Bonds Key Metrics",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/kpi.jsx",
    placeholders: "bonds:kpi",
  },
  {
    key: "bonds:yield",
    marketId: "bonds",
    panelId: "yield",
    title: "Yield Curve",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/yield.jsx",
    placeholders: "bonds:yield",
  },
  {
    key: "bonds:metrics",
    marketId: "bonds",
    panelId: "metrics",
    title: "Spread Monitor",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/metrics.jsx",
    placeholders: "bonds:metrics",
  },
  {
    key: "bonds:credit",
    marketId: "bonds",
    panelId: "credit",
    title: "Credit Spreads",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/credit.jsx",
    placeholders: "bonds:credit",
  },
  {
    key: "bonds:realYield",
    marketId: "bonds",
    panelId: "realYield",
    title: "Real Yields",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/realYield.jsx",
    placeholders: "bonds:realYield",
  },
  {
    key: "bonds:ratings",
    marketId: "bonds",
    panelId: "ratings",
    title: "Credit Ratings",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/ratings.jsx",
    placeholders: "bonds:ratings",
  },
  {
    key: "bonds:curvespreads",
    marketId: "bonds",
    panelId: "curvespreads",
    title: "Curve Spreads",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/curvespreads.jsx",
    placeholders: "bonds:curvespreads",
  },
  {
    key: "bonds:fed",
    marketId: "bonds",
    panelId: "fed",
    title: "Fed Balance Sheet",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/fed.jsx",
    placeholders: "bonds:fed",
  },
  {
    key: "bonds:m2",
    marketId: "bonds",
    panelId: "m2",
    title: "M2 Money Supply",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/m2.jsx",
    placeholders: "bonds:m2",
  },
  {
    key: "bonds:cpi",
    marketId: "bonds",
    panelId: "cpi",
    title: "CPI Components",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/cpi.jsx",
    placeholders: "bonds:cpi",
  },
  {
    key: "bonds:debtgdp",
    marketId: "bonds",
    panelId: "debtgdp",
    title: "Debt-to-GDP",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/debtgdp.jsx",
    placeholders: "bonds:debtgdp",
  },
  {
    key: "bonds:breakevens",
    marketId: "bonds",
    panelId: "breakevens",
    title: "Breakeven Inflation",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/breakevens.jsx",
    placeholders: "bonds:breakevens",
  },
  {
    key: "bonds:duration",
    marketId: "bonds",
    panelId: "duration",
    title: "Duration Ladder",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/duration.jsx",
    placeholders: "bonds:duration",
  },
  {
    key: "bonds:macro",
    marketId: "bonds",
    panelId: "macro",
    title: "Macro Indicators",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/macro.jsx",
    placeholders: "bonds:macro",
  },
  {
    key: "bonds:foreign-holders",
    marketId: "bonds",
    panelId: "foreign-holders",
    title: "Foreign Holders",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/foreign-holders.jsx",
    placeholders: "bonds:foreign-holders",
  },
  {
    key: "bonds:money-market",
    marketId: "bonds",
    panelId: "money-market",
    title: "Money Market",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/money-market.jsx",
    placeholders: "bonds:money-market",
  },
  {
    key: "bonds:auctions",
    marketId: "bonds",
    panelId: "auctions",
    title: "Treasury Auctions",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/auctions.jsx",
    placeholders: "bonds:auctions",
  },
  {
    key: "bonds:ecb-yields",
    marketId: "bonds",
    panelId: "ecb-yields",
    title: "ECB Policy Rates",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/ecbYields.jsx",
    placeholders: "bonds:ecb-yields",
  },
  {
    key: "bonds:global-rates",
    marketId: "bonds",
    panelId: "global-rates",
    title: "Global Central Bank Rates",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/globalRates.jsx",
    placeholders: "bonds:global-rates",
  },
  {
    key: "bonds:treasury-cost",
    marketId: "bonds",
    panelId: "treasury-cost",
    title: "Treasury Avg Interest Cost",
    dashboard: "src/markets/bonds/components/BondsDashboard.jsx",
    module: "src/panels/bonds/treasury-cost.jsx",
    placeholders: "bonds:treasury-cost",
  },
  {
    key: "fx:kpi",
    marketId: "fx",
    panelId: "kpi",
    title: "FX Key Metrics",
    dashboard: "src/markets/fx/components/FXDashboard.jsx",
    module: "src/panels/fx/kpi.jsx",
    placeholders: "fx:kpi",
  },
  {
    key: "fx:sidebar",
    marketId: "fx",
    panelId: "sidebar",
    title: "FX Dashboard",
    dashboard: "src/markets/fx/components/FXDashboard.jsx",
    module: "src/panels/fx/sidebar.jsx",
    placeholders: "fx:sidebar",
  },
  {
    key: "fx:movers",
    marketId: "fx",
    panelId: "movers",
    title: "Top Movers",
    dashboard: "src/markets/fx/components/FXDashboard.jsx",
    module: "src/panels/fx/movers.jsx",
    placeholders: "fx:movers",
  },
  {
    key: "fx:dxy",
    marketId: "fx",
    panelId: "dxy",
    title: "DXY Tracker",
    dashboard: "src/markets/fx/components/FXDashboard.jsx",
    module: "src/panels/fx/dxy.jsx",
    placeholders: "fx:dxy",
  },
  {
    key: "fx:cot",
    marketId: "fx",
    panelId: "cot",
    title: "COT Positioning",
    dashboard: "src/markets/fx/components/FXDashboard.jsx",
    module: "src/panels/fx/cot.jsx",
    placeholders: "fx:cot",
  },
  {
    key: "fx:corr",
    marketId: "fx",
    panelId: "corr",
    title: "Currency Correlation (30D)",
    dashboard: "src/markets/fx/components/FXDashboard.jsx",
    module: "src/panels/fx/corr.jsx",
    placeholders: "fx:corr",
  },
  {
    key: "fx:reer",
    marketId: "fx",
    panelId: "reer",
    title: "REER Chart",
    dashboard: "src/markets/fx/components/FXDashboard.jsx",
    module: "src/panels/fx/reer.jsx",
    placeholders: "fx:reer",
  },
  {
    key: "fx:ratediff",
    marketId: "fx",
    panelId: "ratediff",
    title: "Rate Differentials",
    dashboard: "src/markets/fx/components/FXDashboard.jsx",
    module: "src/panels/fx/ratediff.jsx",
    placeholders: "fx:ratediff",
  },
  {
    key: "fx:carry",
    marketId: "fx",
    panelId: "carry",
    title: "Carry Map",
    dashboard: "src/markets/fx/components/FXDashboard.jsx",
    module: "src/panels/fx/carry.jsx",
    placeholders: "fx:carry",
  },
  {
    key: "fx:rate-dashboard",
    marketId: "fx",
    panelId: "rate-dashboard",
    title: "Rate Dashboard",
    dashboard: "src/markets/fx/components/FXDashboard.jsx",
    module: "src/panels/fx/rate-dashboard.jsx",
    placeholders: "fx:rate-dashboard",
  },
  {
    key: "fx:imf-cofer",
    marketId: "fx",
    panelId: "imf-cofer",
    title: "IMF COFER Reserves",
    dashboard: "src/markets/fx/components/FXDashboard.jsx",
    module: "src/panels/fx/imf-cofer.jsx",
    placeholders: "fx:imf-cofer",
  },
  {
    key: "fx:treasury-tic",
    marketId: "fx",
    panelId: "treasury-tic",
    title: "Treasury TIC Holdings",
    dashboard: "src/markets/fx/components/FXDashboard.jsx",
    module: "src/panels/fx/treasury-tic.jsx",
    placeholders: "fx:treasury-tic",
  },
  {
    key: "derivatives:kpi",
    marketId: "derivatives",
    panelId: "kpi",
    title: "Derivatives Key Metrics",
    dashboard: "src/markets/derivatives/components/DerivativesDashboard.jsx",
    module: "src/panels/derivatives/kpi.jsx",
    placeholders: "derivatives:kpi",
  },
  {
    key: "derivatives:metrics",
    marketId: "derivatives",
    panelId: "metrics",
    title: "Key Metrics",
    dashboard: "src/markets/derivatives/components/DerivativesDashboard.jsx",
    module: "src/panels/derivatives/metrics.jsx",
    placeholders: "derivatives:metrics",
  },
  {
    key: "derivatives:vixterm",
    marketId: "derivatives",
    panelId: "vixterm",
    title: "VIX Term Structure",
    dashboard: "src/markets/derivatives/components/DerivativesDashboard.jsx",
    module: "src/panels/derivatives/vixterm.jsx",
    placeholders: "derivatives:vixterm",
  },
  {
    key: "derivatives:vix1y",
    marketId: "derivatives",
    panelId: "vix1y",
    title: "VIX — 1 Year",
    dashboard: "src/markets/derivatives/components/DerivativesDashboard.jsx",
    module: "src/panels/derivatives/vix1y.jsx",
    placeholders: "derivatives:vix1y",
  },
  {
    key: "derivatives:skew",
    marketId: "derivatives",
    panelId: "skew",
    title: "Skew Index",
    dashboard: "src/markets/derivatives/components/DerivativesDashboard.jsx",
    module: "src/panels/derivatives/skew.jsx",
    placeholders: "derivatives:skew",
  },
  {
    key: "derivatives:volsurf",
    marketId: "derivatives",
    panelId: "volsurf",
    title: "Vol Surface",
    dashboard: "src/markets/derivatives/components/DerivativesDashboard.jsx",
    module: "src/panels/derivatives/volsurf.jsx",
    placeholders: "derivatives:volsurf",
  },
  {
    key: "derivatives:flow",
    marketId: "derivatives",
    panelId: "flow",
    title: "Options Flow",
    dashboard: "src/markets/derivatives/components/DerivativesDashboard.jsx",
    module: "src/panels/derivatives/flow.jsx",
    placeholders: "derivatives:flow",
  },
  {
    key: "derivatives:gamma",
    marketId: "derivatives",
    panelId: "gamma",
    title: "Gamma Exposure",
    dashboard: "src/markets/derivatives/components/DerivativesDashboard.jsx",
    module: "src/panels/derivatives/gamma.jsx",
    placeholders: "derivatives:gamma",
  },
  {
    key: "derivatives:volprem",
    marketId: "derivatives",
    panelId: "volprem",
    title: "Vol Premium",
    dashboard: "src/markets/derivatives/components/DerivativesDashboard.jsx",
    module: "src/panels/derivatives/volprem.jsx",
    placeholders: "derivatives:volprem",
  },
  {
    key: "derivatives:cftc-tff",
    marketId: "derivatives",
    panelId: "cftc-tff",
    title: "CFTC Financial Futures",
    dashboard: "src/markets/derivatives/components/DerivativesDashboard.jsx",
    module: "src/panels/derivatives/cftc-tff.jsx",
    placeholders: "derivatives:cftc-tff",
  },
  {
    key: "derivatives:bis-otc",
    marketId: "derivatives",
    panelId: "bis-otc",
    title: "BIS OTC Derivatives",
    dashboard: "src/markets/derivatives/components/DerivativesDashboard.jsx",
    module: "src/panels/derivatives/bis-otc.jsx",
    placeholders: "derivatives:bis-otc",
  },
  {
    key: "derivatives:ecb-derivatives",
    marketId: "derivatives",
    panelId: "ecb-derivatives",
    title: "ECB Financial Market Data",
    dashboard: "src/markets/derivatives/components/DerivativesDashboard.jsx",
    module: "src/panels/derivatives/ecb-derivatives.jsx",
    placeholders: "derivatives:ecb-derivatives",
  },
  {
    key: "realEstate:metrics",
    marketId: "realEstate",
    panelId: "metrics",
    title: "Key Metrics",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/metrics.jsx",
    placeholders: "realEstate:metrics",
  },
  {
    key: "realEstate:shiller",
    marketId: "realEstate",
    panelId: "shiller",
    title: "Case-Shiller Index",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/shiller.jsx",
    placeholders: "realEstate:shiller",
  },
  {
    key: "realEstate:reitetf",
    marketId: "realEstate",
    panelId: "reitetf",
    title: "REIT ETF (VNQ)",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/reitetf.jsx",
    placeholders: "realEstate:reitetf",
  },
  {
    key: "realEstate:reitperf",
    marketId: "realEstate",
    panelId: "reitperf",
    title: "REIT Performance",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/reitperf.jsx",
    placeholders: "realEstate:reitperf",
  },
  {
    key: "realEstate:foreclosure",
    marketId: "realEstate",
    panelId: "foreclosure",
    title: "Distress Indicators",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/foreclosure.jsx",
    placeholders: "realEstate:foreclosure",
  },
  {
    key: "realEstate:mba",
    marketId: "realEstate",
    panelId: "mba",
    title: "Mortgage Rates",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/mba.jsx",
    placeholders: "realEstate:mba",
  },
  {
    key: "realEstate:cre",
    marketId: "realEstate",
    panelId: "cre",
    title: "CRE Delinquencies",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/cre.jsx",
    placeholders: "realEstate:cre",
  },
  {
    key: "realEstate:caprate",
    marketId: "realEstate",
    panelId: "caprate",
    title: "Cap Rates by Sector",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/caprate.jsx",
    placeholders: "realEstate:caprate",
  },
  {
    key: "realEstate:supply",
    marketId: "realEstate",
    panelId: "supply",
    title: "Supply & Demand",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/supply.jsx",
    placeholders: "realEstate:supply",
  },
  {
    key: "realEstate:hud-afford",
    marketId: "realEstate",
    panelId: "hud-afford",
    title: "HUD Rental Affordability",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/hud-afford.jsx",
    placeholders: "realEstate:hud-afford",
  },
  {
    key: "realEstate:afford-stack",
    marketId: "realEstate",
    panelId: "afford-stack",
    title: "Housing Affordability Stack",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/afford-stack.jsx",
    placeholders: "realEstate:afford-stack",
  },
  {
    key: "realEstate:census-housing",
    marketId: "realEstate",
    panelId: "census-housing",
    title: "Census Housing KPI",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/census-housing.jsx",
    placeholders: "realEstate:census-housing",
  },
  {
    key: "realEstate:census-trade",
    marketId: "realEstate",
    panelId: "census-trade",
    title: "Census Trade KPI",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/census-trade.jsx",
    placeholders: "realEstate:census-trade",
  },
  {
    key: "realEstate:census-trends-housing",
    marketId: "realEstate",
    panelId: "census-trends-housing",
    title: "Census Housing Trends",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/census-trends-housing.jsx",
    placeholders: "realEstate:census-trends-housing",
  },
  {
    key: "realEstate:census-trends-trade",
    marketId: "realEstate",
    panelId: "census-trends-trade",
    title: "Census Trade Trends",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/census-trends-trade.jsx",
    placeholders: "realEstate:census-trends-trade",
  },
  {
    key: "realEstate:fhfa-hpi",
    marketId: "realEstate",
    panelId: "fhfa-hpi",
    title: "FHFA House Price Index",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/fhfa-hpi.jsx",
    placeholders: "realEstate:fhfa-hpi",
  },
  {
    key: "realEstate:bis-property-prices",
    marketId: "realEstate",
    panelId: "bis-property-prices",
    title: "BIS Property Price Comparison",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/bis-property-prices.jsx",
    placeholders: "realEstate:bis-property-prices",
  },
  {
    key: "realEstate:metro-case-shiller",
    marketId: "realEstate",
    panelId: "metro-case-shiller",
    title: "Metro Case-Shiller",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/metro-case-shiller.jsx",
    placeholders: "realEstate:metro-case-shiller",
  },
  {
    key: "realEstate:hud-affordability-by-metro",
    marketId: "realEstate",
    panelId: "hud-affordability-by-metro",
    title: "HUD Affordability by Metro",
    dashboard: "src/markets/realEstate/components/RealEstateDashboard.jsx",
    module: "src/panels/realEstate/hud-affordability-by-metro.jsx",
    placeholders: "realEstate:hud-affordability-by-metro",
  },
  {
    key: "insurance:kpi",
    marketId: "insurance",
    panelId: "kpi",
    title: "Insurance Key Metrics",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/kpi.jsx",
    placeholders: "insurance:kpi",
  },
  {
    key: "insurance:hyoas",
    marketId: "insurance",
    panelId: "hyoas",
    title: "HY OAS Spread",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/hyoas.jsx",
    placeholders: "insurance:hyoas",
  },
  {
    key: "insurance:catloss",
    marketId: "insurance",
    panelId: "catloss",
    title: "Natural Catastrophe Losses",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/catloss.jsx",
    placeholders: "insurance:catloss",
  },
  {
    key: "insurance:crhist",
    marketId: "insurance",
    panelId: "crhist",
    title: "Industry Combined Ratio",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/crhist.jsx",
    placeholders: "insurance:crhist",
  },
  {
    key: "insurance:crline",
    marketId: "insurance",
    panelId: "crline",
    title: "Combined Ratio by Line",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/crline.jsx",
    placeholders: "insurance:crline",
  },
  {
    key: "insurance:reinsrates",
    marketId: "insurance",
    panelId: "reinsrates",
    title: "Reinsurance Pricing",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/reinsrates.jsx",
    placeholders: "insurance:reinsrates",
  },
  {
    key: "insurance:reserves",
    marketId: "insurance",
    panelId: "reserves",
    title: "Reserve Adequacy",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/reserves.jsx",
    placeholders: "insurance:reserves",
  },
  {
    key: "insurance:catbonds",
    marketId: "insurance",
    panelId: "catbonds",
    title: "Cat Bond Spreads",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/catbonds.jsx",
    placeholders: "insurance:catbonds",
  },
  {
    key: "insurance:etfs",
    marketId: "insurance",
    panelId: "etfs",
    title: "Sector / Industry Pulse",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/etfs.jsx",
    placeholders: "insurance:etfs",
  },
  {
    key: "insurance:catastrophes",
    marketId: "insurance",
    panelId: "catastrophes",
    title: "Catastrophes (FEMA+USGS)",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/catastrophes.jsx",
    placeholders: "insurance:catastrophes",
  },
  {
    key: "insurance:ins-penetration",
    marketId: "insurance",
    panelId: "ins-penetration",
    title: "Insurance Penetration",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/ins-penetration.jsx",
    placeholders: "insurance:ins-penetration",
  },
  {
    key: "insurance:combined-ratios",
    marketId: "insurance",
    panelId: "combined-ratios",
    title: "Insurer Combined Ratios (EDGAR)",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/combined-ratios.jsx",
    placeholders: "insurance:combined-ratios",
  },
  {
    key: "insurance:fema-disasters",
    marketId: "insurance",
    panelId: "fema-disasters",
    title: "FEMA Disaster Declarations",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/fema-disasters.jsx",
    placeholders: "insurance:fema-disasters",
  },
  {
    key: "insurance:usgs-earthquakes",
    marketId: "insurance",
    panelId: "usgs-earthquakes",
    title: "USGS Earthquake Activity",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/usgs-earthquakes.jsx",
    placeholders: "insurance:usgs-earthquakes",
  },
  {
    key: "insurance:cat-exposure",
    marketId: "insurance",
    panelId: "cat-exposure",
    title: "Cat Exposure",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/cat-exposure.jsx",
    placeholders: "insurance:cat-exposure",
  },
  {
    key: "insurance:usgs-minerals",
    marketId: "insurance",
    panelId: "usgs-minerals",
    title: "USGS Earthquake Activity (30d)",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/usgs-minerals.jsx",
    placeholders: "insurance:usgs-minerals",
  },
  {
    key: "insurance:ecb-supervisory",
    marketId: "insurance",
    panelId: "ecb-supervisory",
    title: "ECB Policy Rates",
    dashboard: "src/markets/insurance/components/InsuranceDashboard.jsx",
    module: "src/panels/insurance/ecb-supervisory.jsx",
    placeholders: "insurance:ecb-supervisory",
  },
  {
    key: "commodities:sidebar",
    marketId: "commodities",
    panelId: "sidebar",
    title: "Market Summary",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/sidebar.jsx",
    placeholders: "commodities:sidebar",
  },
  {
    key: "commodities:prices",
    marketId: "commodities",
    panelId: "prices",
    title: "Commodity Prices",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/prices.jsx",
    placeholders: "commodities:prices",
  },
  {
    key: "commodities:futures",
    marketId: "commodities",
    panelId: "futures",
    title: "Futures Curve",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/futures.jsx",
    placeholders: "commodities:futures",
  },
  {
    key: "commodities:sector",
    marketId: "commodities",
    panelId: "sector",
    title: "Sector Performance",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/sector.jsx",
    placeholders: "commodities:sector",
  },
  {
    key: "commodities:supply",
    marketId: "commodities",
    panelId: "supply",
    title: "Supply & Demand",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/supply.jsx",
    placeholders: "commodities:supply",
  },
  {
    key: "commodities:wti-brent",
    marketId: "commodities",
    panelId: "wti-brent",
    title: "WTI vs Brent Spread",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/wti-brent.jsx",
    placeholders: "commodities:wti-brent",
  },
  {
    key: "commodities:cot",
    marketId: "commodities",
    panelId: "cot",
    title: "COT Positioning",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/cot.jsx",
    placeholders: "commodities:cot",
  },
  {
    key: "commodities:comfx",
    marketId: "commodities",
    panelId: "comfx",
    title: "Commodity FX (vs USD)",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/comfx.jsx",
    placeholders: "commodities:comfx",
  },
  {
    key: "commodities:usda-ag",
    marketId: "commodities",
    panelId: "usda-ag",
    title: "US Ag Commodity Prices",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/usda-ag.jsx",
    placeholders: "commodities:usda-ag",
  },
  {
    key: "commodities:eia-petrol",
    marketId: "commodities",
    panelId: "eia-petrol",
    title: "Petroleum & Natural Gas",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/eia-petrol.jsx",
    placeholders: "commodities:eia-petrol",
  },
  {
    key: "commodities:physical-pressure",
    marketId: "commodities",
    panelId: "physical-pressure",
    title: "Physical Pressure",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/physical-pressure.jsx",
    placeholders: "commodities:physical-pressure",
  },
  {
    key: "commodities:materials-grid",
    marketId: "commodities",
    panelId: "materials-grid",
    title: "Strategic Materials Grid",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/materials-grid.jsx",
    placeholders: "commodities:materials-grid",
  },
  {
    key: "commodities:criticality",
    marketId: "commodities",
    panelId: "criticality",
    title: "Criticality Leaderboard",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/criticality.jsx",
    placeholders: "commodities:criticality",
  },
  {
    key: "commodities:battery-chain",
    marketId: "commodities",
    panelId: "battery-chain",
    title: "Battery Supply Chain",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/battery-chain.jsx",
    placeholders: "commodities:battery-chain",
  },
  {
    key: "commodities:precious-complex",
    marketId: "commodities",
    panelId: "precious-complex",
    title: "Precious Metals Complex",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/precious-complex.jsx",
    placeholders: "commodities:precious-complex",
  },
  {
    key: "commodities:regime",
    marketId: "commodities",
    panelId: "regime",
    title: "Commodity Regime Dashboard",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/regime.jsx",
    placeholders: "commodities:regime",
  },
  {
    key: "commodities:energy-stack",
    marketId: "commodities",
    panelId: "energy-stack",
    title: "Energy Stack",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/energy-stack.jsx",
    placeholders: "commodities:energy-stack",
  },
  {
    key: "commodities:curve-board",
    marketId: "commodities",
    panelId: "curve-board",
    title: "Curve Structure Board",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/curve-board.jsx",
    placeholders: "commodities:curve-board",
  },
  {
    key: "commodities:material-detail",
    marketId: "commodities",
    panelId: "material-detail",
    title: "Strategic Material Detail",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/material-detail.jsx",
    placeholders: "commodities:material-detail",
  },
  {
    key: "commodities:exposure-matrix",
    marketId: "commodities",
    panelId: "exposure-matrix",
    title: "Material-to-Sector Exposure Matrix",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/exposure-matrix.jsx",
    placeholders: "commodities:exposure-matrix",
  },
  {
    key: "commodities:fao-prices",
    marketId: "commodities",
    panelId: "fao-prices",
    title: "FAO Food Price Index",
    dashboard: "src/markets/commodities/components/CommoditiesDashboard.jsx",
    module: "src/panels/commodities/fao-prices.jsx",
    placeholders: "commodities:fao-prices",
  },
  {
    key: "globalMacro:kpi",
    marketId: "globalMacro",
    panelId: "kpi",
    title: "Macro Key Metrics",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/kpi.jsx",
    placeholders: "globalMacro:kpi",
  },
  {
    key: "globalMacro:sidebar",
    marketId: "globalMacro",
    panelId: "sidebar",
    title: "Macro Summary",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/sidebar.jsx",
    placeholders: "globalMacro:sidebar",
  },
  {
    key: "globalMacro:scorecard",
    marketId: "globalMacro",
    panelId: "scorecard",
    title: "Scorecard",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/scorecard.jsx",
    placeholders: "globalMacro:scorecard",
  },
  {
    key: "globalMacro:gdp",
    marketId: "globalMacro",
    panelId: "gdp",
    title: "GDP Growth",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/gdp.jsx",
    placeholders: "globalMacro:gdp",
  },
  {
    key: "globalMacro:cpi",
    marketId: "globalMacro",
    panelId: "cpi",
    title: "CPI Inflation",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/cpi.jsx",
    placeholders: "globalMacro:cpi",
  },
  {
    key: "globalMacro:rates",
    marketId: "globalMacro",
    panelId: "rates",
    title: "Central Bank Rates",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/rates.jsx",
    placeholders: "globalMacro:rates",
  },
  {
    key: "globalMacro:debt",
    marketId: "globalMacro",
    panelId: "debt",
    title: "Debt Monitor",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/debt.jsx",
    placeholders: "globalMacro:debt",
  },
  {
    key: "globalMacro:activity",
    marketId: "globalMacro",
    panelId: "activity",
    title: "Economic Activity",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/activity.jsx",
    placeholders: "globalMacro:activity",
  },
  {
    key: "globalMacro:cli",
    marketId: "globalMacro",
    panelId: "cli",
    title: "OECD Leading Indicators",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/cli.jsx",
    placeholders: "globalMacro:cli",
  },
  {
    key: "globalMacro:imf-reserves",
    marketId: "globalMacro",
    panelId: "imf-reserves",
    title: "IMF Reserves",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/imf-reserves.jsx",
    placeholders: "globalMacro:imf-reserves",
  },
  {
    key: "globalMacro:imf-cofer",
    marketId: "globalMacro",
    panelId: "imf-cofer",
    title: "IMF COFER",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/imf-cofer.jsx",
    placeholders: "globalMacro:imf-cofer",
  },
  {
    key: "globalMacro:wb-trade",
    marketId: "globalMacro",
    panelId: "wb-trade",
    title: "World Bank Trade Openness",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/wb-trade.jsx",
    placeholders: "globalMacro:wb-trade",
  },
  {
    key: "globalMacro:wb-dev",
    marketId: "globalMacro",
    panelId: "wb-dev",
    title: "World Bank GDP per Capita",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/wb-dev.jsx",
    placeholders: "globalMacro:wb-dev",
  },
  {
    key: "globalMacro:ecb-eur",
    marketId: "globalMacro",
    panelId: "ecb-eur",
    title: "ECB Euro Area",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/ecb-eur.jsx",
    placeholders: "globalMacro:ecb-eur",
  },
  {
    key: "globalMacro:tga-balance",
    marketId: "globalMacro",
    panelId: "tga-balance",
    title: "TGA Cash Balance",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/tga-balance.jsx",
    placeholders: "globalMacro:tga-balance",
  },
  {
    key: "globalMacro:gdpnow",
    marketId: "globalMacro",
    panelId: "gdpnow",
    title: "GDPNow",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/gdpnow.jsx",
    placeholders: "globalMacro:gdpnow",
  },
  {
    key: "globalMacro:fomc-sep",
    marketId: "globalMacro",
    panelId: "fomc-sep",
    title: "FOMC SEP",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/fomc-sep.jsx",
    placeholders: "globalMacro:fomc-sep",
  },
  {
    key: "globalMacro:cleveland",
    marketId: "globalMacro",
    panelId: "cleveland",
    title: "Cleveland Inflation Nowcast",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/cleveland.jsx",
    placeholders: "globalMacro:cleveland",
  },
  {
    key: "globalMacro:bea-accounts",
    marketId: "globalMacro",
    panelId: "bea-accounts",
    title: "BEA National Accounts",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/bea-accounts.jsx",
    placeholders: "globalMacro:bea-accounts",
  },
  {
    key: "globalMacro:eurostat",
    marketId: "globalMacro",
    panelId: "eurostat",
    title: "Eurostat Macro",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/eurostat.jsx",
    placeholders: "globalMacro:eurostat",
  },
  {
    key: "globalMacro:oecd-direct",
    marketId: "globalMacro",
    panelId: "oecd-direct",
    title: "OECD Direct",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/oecd-direct.jsx",
    placeholders: "globalMacro:oecd-direct",
  },
  {
    key: "globalMacro:bea-income",
    marketId: "globalMacro",
    panelId: "bea-income",
    title: "BEA Income",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/bea-income.jsx",
    placeholders: "globalMacro:bea-income",
  },
  {
    key: "globalMacro:global-liquidity",
    marketId: "globalMacro",
    panelId: "global-liquidity",
    title: "BIS Global Liquidity",
    dashboard: "src/markets/globalMacro/components/GlobalMacroDashboard.jsx",
    module: "src/panels/globalMacro/global-liquidity.jsx",
    placeholders: "globalMacro:global-liquidity",
  },
  {
    key: "equitiesDeepDive:kpi",
    marketId: "equitiesDeepDive",
    panelId: "kpi",
    title: "Equity+ Key Metrics",
    dashboard: "src/markets/equitiesDeepDive/components/EquitiesDeepDiveDashboard.jsx",
    module: "src/panels/equitiesDeepDive/kpi.jsx",
    placeholders: "equitiesDeepDive:kpi",
  },
  {
    key: "equitiesDeepDive:sidebar",
    marketId: "equitiesDeepDive",
    panelId: "sidebar",
    title: "Equity+ Summary",
    dashboard: "src/markets/equitiesDeepDive/components/EquitiesDeepDiveDashboard.jsx",
    module: "src/panels/equitiesDeepDive/sidebar.jsx",
    placeholders: "equitiesDeepDive:sidebar",
  },
  {
    key: "equitiesDeepDive:valuation",
    marketId: "equitiesDeepDive",
    panelId: "valuation",
    title: "Key Metrics",
    dashboard: "src/markets/equitiesDeepDive/components/EquitiesDeepDiveDashboard.jsx",
    module: "src/panels/equitiesDeepDive/valuation.jsx",
    placeholders: "equitiesDeepDive:valuation",
  },
  {
    key: "equitiesDeepDive:etf",
    marketId: "equitiesDeepDive",
    panelId: "etf",
    title: "ETF Performance",
    dashboard: "src/markets/equitiesDeepDive/components/EquitiesDeepDiveDashboard.jsx",
    module: "src/panels/equitiesDeepDive/etf.jsx",
    placeholders: "equitiesDeepDive:etf",
  },
  {
    key: "equitiesDeepDive:factor-favor",
    marketId: "equitiesDeepDive",
    panelId: "factor-favor",
    title: "Factor In Favor",
    dashboard: "src/markets/equitiesDeepDive/components/EquitiesDeepDiveDashboard.jsx",
    module: "src/panels/equitiesDeepDive/factor-favor.jsx",
    placeholders: "equitiesDeepDive:factor-favor",
  },
  {
    key: "equitiesDeepDive:sector-beat",
    marketId: "equitiesDeepDive",
    panelId: "sector-beat",
    title: "Sector Beat Rate",
    dashboard: "src/markets/equitiesDeepDive/components/EquitiesDeepDiveDashboard.jsx",
    module: "src/panels/equitiesDeepDive/sector-beat.jsx",
    placeholders: "equitiesDeepDive:sector-beat",
  },
  {
    key: "equitiesDeepDive:shorted",
    marketId: "equitiesDeepDive",
    panelId: "shorted",
    title: "Most Shorted",
    dashboard: "src/markets/equitiesDeepDive/components/EquitiesDeepDiveDashboard.jsx",
    module: "src/panels/equitiesDeepDive/shorted.jsx",
    placeholders: "equitiesDeepDive:shorted",
  },
  {
    key: "equitiesDeepDive:scores",
    marketId: "equitiesDeepDive",
    panelId: "scores",
    title: "Stock Factor Scores",
    dashboard: "src/markets/equitiesDeepDive/components/EquitiesDeepDiveDashboard.jsx",
    module: "src/panels/equitiesDeepDive/scores.jsx",
    placeholders: "equitiesDeepDive:scores",
  },
  {
    key: "equitiesDeepDive:earnings",
    marketId: "equitiesDeepDive",
    panelId: "earnings",
    title: "Upcoming Earnings",
    dashboard: "src/markets/equitiesDeepDive/components/EquitiesDeepDiveDashboard.jsx",
    module: "src/panels/equitiesDeepDive/earnings.jsx",
    placeholders: "equitiesDeepDive:earnings",
  },
  {
    key: "equitiesDeepDive:institutions",
    marketId: "equitiesDeepDive",
    panelId: "institutions",
    title: "Top Institutions",
    dashboard: "src/markets/equitiesDeepDive/components/EquitiesDeepDiveDashboard.jsx",
    module: "src/panels/equitiesDeepDive/institutions.jsx",
    placeholders: "equitiesDeepDive:institutions",
  },
  {
    key: "equitiesDeepDive:insider",
    marketId: "equitiesDeepDive",
    panelId: "insider",
    title: "Insider Trading",
    dashboard: "src/markets/equitiesDeepDive/components/EquitiesDeepDiveDashboard.jsx",
    module: "src/panels/equitiesDeepDive/insider.jsx",
    placeholders: "equitiesDeepDive:insider",
  },
  {
    key: "equitiesDeepDive:earnings-quality",
    marketId: "equitiesDeepDive",
    panelId: "earnings-quality",
    title: "Earnings Quality & Revision Monitor",
    dashboard: "src/markets/equitiesDeepDive/components/EquitiesDeepDiveDashboard.jsx",
    module: "src/panels/equitiesDeepDive/earnings-quality.jsx",
    placeholders: "equitiesDeepDive:earnings-quality",
  },
  {
    key: "crypto:sidebar",
    marketId: "crypto",
    panelId: "sidebar",
    title: "Crypto Summary",
    dashboard: "src/markets/crypto/components/CryptoDashboard.jsx",
    module: "src/panels/crypto/sidebar.jsx",
    placeholders: "crypto:sidebar",
  },
  {
    key: "crypto:top-cryptos",
    marketId: "crypto",
    panelId: "top-cryptos",
    title: "Top Cryptos",
    dashboard: "src/markets/crypto/components/CryptoDashboard.jsx",
    module: "src/panels/crypto/top-cryptos.jsx",
    placeholders: "crypto:top-cryptos",
  },
  {
    key: "crypto:fear-greed",
    marketId: "crypto",
    panelId: "fear-greed",
    title: "Fear & Greed Index",
    dashboard: "src/markets/crypto/components/CryptoDashboard.jsx",
    module: "src/panels/crypto/fear-greed.jsx",
    placeholders: "crypto:fear-greed",
  },
  {
    key: "crypto:funding",
    marketId: "crypto",
    panelId: "funding",
    title: "Funding Rates",
    dashboard: "src/markets/crypto/components/CryptoDashboard.jsx",
    module: "src/panels/crypto/funding.jsx",
    placeholders: "crypto:funding",
  },
  {
    key: "crypto:defi-tvl",
    marketId: "crypto",
    panelId: "defi-tvl",
    title: "DeFi TVL by Chain",
    dashboard: "src/markets/crypto/components/CryptoDashboard.jsx",
    module: "src/panels/crypto/defi-tvl.jsx",
    placeholders: "crypto:defi-tvl",
  },
  {
    key: "crypto:exchanges",
    marketId: "crypto",
    panelId: "exchanges",
    title: "Top Exchanges",
    dashboard: "src/markets/crypto/components/CryptoDashboard.jsx",
    module: "src/panels/crypto/exchanges.jsx",
    placeholders: "crypto:exchanges",
  },
  {
    key: "crypto:onchain",
    marketId: "crypto",
    panelId: "onchain",
    title: "On-Chain Metrics",
    dashboard: "src/markets/crypto/components/CryptoDashboard.jsx",
    module: "src/panels/crypto/onchain.jsx",
    placeholders: "crypto:onchain",
  },
  {
    key: "crypto:onchain-chart",
    marketId: "crypto",
    panelId: "onchain-chart",
    title: "BTC Hashrate (30d)",
    dashboard: "src/markets/crypto/components/CryptoDashboard.jsx",
    module: "src/panels/crypto/onchain-chart.jsx",
    placeholders: "crypto:onchain-chart",
  },
  {
    key: "crypto:stablecoin-composition",
    marketId: "crypto",
    panelId: "stablecoin-composition",
    title: "Stablecoin Composition",
    dashboard: "src/markets/crypto/components/CryptoDashboard.jsx",
    module: "src/panels/crypto/stablecoin-composition.jsx",
    placeholders: "crypto:stablecoin-composition",
  },
  {
    key: "crypto:defi-tvl-trend",
    marketId: "crypto",
    panelId: "defi-tvl-trend",
    title: "DeFi TVL Trend",
    dashboard: "src/markets/crypto/components/CryptoDashboard.jsx",
    module: "src/panels/crypto/defi-tvl-trend.jsx",
    placeholders: "crypto:defi-tvl-trend",
  },
  {
    key: "crypto:btc-onchain",
    marketId: "crypto",
    panelId: "btc-onchain",
    title: "BTC On-Chain Activity",
    dashboard: "src/markets/crypto/components/CryptoDashboard.jsx",
    module: "src/panels/crypto/btc-onchain.jsx",
    placeholders: "crypto:btc-onchain",
  },
  {
    key: "credit:kpi",
    marketId: "credit",
    panelId: "kpi",
    title: "Credit Key Metrics",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/kpi.jsx",
    placeholders: "credit:kpi",
  },
  {
    key: "credit:key-metrics",
    marketId: "credit",
    panelId: "key-metrics",
    title: "Key Metrics",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/key-metrics.jsx",
    placeholders: "credit:key-metrics",
  },
  {
    key: "credit:credit-spreads",
    marketId: "credit",
    panelId: "credit-spreads",
    title: "Credit Spreads",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/credit-spreads.jsx",
    placeholders: "credit:credit-spreads",
  },
  {
    key: "credit:spread-summary",
    marketId: "credit",
    panelId: "spread-summary",
    title: "Spread Summary",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/spread-summary.jsx",
    placeholders: "credit:spread-summary",
  },
  {
    key: "credit:em-yields",
    marketId: "credit",
    panelId: "em-yields",
    title: "EM ETF Yields",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/em-yields.jsx",
    placeholders: "credit:em-yields",
  },
  {
    key: "credit:cp-rates",
    marketId: "credit",
    panelId: "cp-rates",
    title: "Commercial Paper",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/cp-rates.jsx",
    placeholders: "credit:cp-rates",
  },
  {
    key: "credit:clo-tranches",
    marketId: "credit",
    panelId: "clo-tranches",
    title: "CLO Tranches",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/clo-tranches.jsx",
    placeholders: "credit:clo-tranches",
  },
  {
    key: "credit:default-rates",
    marketId: "credit",
    panelId: "default-rates",
    title: "Default Rates",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/default-rates.jsx",
    placeholders: "credit:default-rates",
  },
  {
    key: "credit:delinquency",
    marketId: "credit",
    panelId: "delinquency",
    title: "Delinquency Rates",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/delinquency.jsx",
    placeholders: "credit:delinquency",
  },
  {
    key: "credit:bank-sector",
    marketId: "credit",
    panelId: "bank-sector",
    title: "US Banking Sector (FDIC)",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/bank-sector.jsx",
    placeholders: "credit:bank-sector",
  },
  {
    key: "credit:muni-market",
    marketId: "credit",
    panelId: "muni-market",
    title: "US Municipal Bond Market (MSRB)",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/muni-market.jsx",
    placeholders: "credit:muni-market",
  },
  {
    key: "credit:bank-stress",
    marketId: "credit",
    panelId: "bank-stress",
    title: "Bank Stress Monitor",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/bank-stress.jsx",
    placeholders: "credit:bank-stress",
  },
  {
    key: "credit:ted-spread",
    marketId: "credit",
    panelId: "ted-spread",
    title: "TED Spread",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/ted-spread.jsx",
    placeholders: "credit:ted-spread",
  },
  {
    key: "credit:wb-debt",
    marketId: "credit",
    panelId: "wb-debt",
    title: "World Bank Debt Statistics",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/wb-debt.jsx",
    placeholders: "credit:wb-debt",
  },
  {
    key: "credit:bis-total-credit",
    marketId: "credit",
    panelId: "bis-total-credit",
    title: "BIS Total Credit",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/bis-total-credit.jsx",
    placeholders: "credit:bis-total-credit",
  },
  {
    key: "credit:treasury-credit-holdings",
    marketId: "credit",
    panelId: "treasury-credit-holdings",
    title: "Treasury Credit Holdings",
    dashboard: "src/markets/credit/components/CreditDashboard.jsx",
    module: "src/panels/credit/treasury-credit-holdings.jsx",
    placeholders: "credit:treasury-credit-holdings",
  },
  {
    key: "sentiment:sidebar",
    marketId: "sentiment",
    panelId: "sidebar",
    title: "Market Snapshot",
    dashboard: "src/markets/sentiment/components/SentimentDashboard.jsx",
    module: "src/panels/sentiment/sidebar.jsx",
    placeholders: "sentiment:sidebar",
  },
  {
    key: "sentiment:key-metrics",
    marketId: "sentiment",
    panelId: "key-metrics",
    title: "Key Metrics",
    dashboard: "src/markets/sentiment/components/SentimentDashboard.jsx",
    module: "src/panels/sentiment/key-metrics.jsx",
    placeholders: "sentiment:key-metrics",
  },
  {
    key: "sentiment:fear-greed",
    marketId: "sentiment",
    panelId: "fear-greed",
    title: "Fear & Greed Index",
    dashboard: "src/markets/sentiment/components/SentimentDashboard.jsx",
    module: "src/panels/sentiment/fear-greed.jsx",
    placeholders: "sentiment:fear-greed",
  },
  {
    key: "sentiment:fsi",
    marketId: "sentiment",
    panelId: "fsi",
    title: "Financial Stress Index",
    dashboard: "src/markets/sentiment/components/SentimentDashboard.jsx",
    module: "src/panels/sentiment/fsi.jsx",
    placeholders: "sentiment:fsi",
  },
  {
    key: "sentiment:cftc",
    marketId: "sentiment",
    panelId: "cftc",
    title: "CFTC Positioning",
    dashboard: "src/markets/sentiment/components/SentimentDashboard.jsx",
    module: "src/panels/sentiment/cftc.jsx",
    placeholders: "sentiment:cftc",
  },
  {
    key: "sentiment:cross-asset",
    marketId: "sentiment",
    panelId: "cross-asset",
    title: "Cross-Asset Returns",
    dashboard: "src/markets/sentiment/components/SentimentDashboard.jsx",
    module: "src/panels/sentiment/cross-asset.jsx",
    placeholders: "sentiment:cross-asset",
  },
  {
    key: "sentiment:risk-dashboard",
    marketId: "sentiment",
    panelId: "risk-dashboard",
    title: "Risk Dashboard",
    dashboard: "src/markets/sentiment/components/SentimentDashboard.jsx",
    module: "src/panels/sentiment/risk-dashboard.jsx",
    placeholders: "sentiment:risk-dashboard",
  },
  {
    key: "sentiment:leverage",
    marketId: "sentiment",
    panelId: "leverage",
    title: "Leverage Metrics",
    dashboard: "src/markets/sentiment/components/SentimentDashboard.jsx",
    module: "src/panels/sentiment/leverage.jsx",
    placeholders: "sentiment:leverage",
  },
  {
    key: "sentiment:news-sentiment",
    marketId: "sentiment",
    panelId: "news-sentiment",
    title: "Daily News Sentiment Index (SF Fed)",
    dashboard: "src/markets/sentiment/components/SentimentDashboard.jsx",
    module: "src/panels/sentiment/news-sentiment.jsx",
    placeholders: "sentiment:news-sentiment",
  },
  {
    key: "sentiment:fed-risk-mood",
    marketId: "sentiment",
    panelId: "fed-risk-mood",
    title: "Fed Narrative & Risk Mood",
    dashboard: "src/markets/sentiment/components/SentimentDashboard.jsx",
    module: "src/panels/sentiment/fed-risk-mood.jsx",
    placeholders: "sentiment:fed-risk-mood",
  },
  {
    key: "calendar:kpi",
    marketId: "calendar",
    panelId: "kpi",
    title: "Calendar Key Metrics",
    dashboard: "src/markets/calendar/components/CalendarDashboard.jsx",
    module: "src/panels/calendar/kpi.jsx",
    placeholders: "calendar:kpi",
  },
  {
    key: "calendar:economic",
    marketId: "calendar",
    panelId: "economic",
    title: "Economic Calendar",
    dashboard: "src/markets/calendar/components/CalendarDashboard.jsx",
    module: "src/panels/calendar/economic.jsx",
    placeholders: "calendar:economic",
  },
  {
    key: "calendar:sidebar",
    marketId: "calendar",
    panelId: "sidebar",
    title: "Calendar Summary",
    dashboard: "src/markets/calendar/components/CalendarDashboard.jsx",
    module: "src/panels/calendar/sidebar.jsx",
    placeholders: "calendar:sidebar",
  },
  {
    key: "calendar:cb-rates",
    marketId: "calendar",
    panelId: "cb-rates",
    title: "Central Bank Rates",
    dashboard: "src/markets/calendar/components/CalendarDashboard.jsx",
    module: "src/panels/calendar/cb-rates.jsx",
    placeholders: "calendar:cb-rates",
  },
  {
    key: "calendar:cb-timeline",
    marketId: "calendar",
    panelId: "cb-timeline",
    title: "Upcoming Meetings",
    dashboard: "src/markets/calendar/components/CalendarDashboard.jsx",
    module: "src/panels/calendar/cb-timeline.jsx",
    placeholders: "calendar:cb-timeline",
  },
  {
    key: "calendar:earnings",
    marketId: "calendar",
    panelId: "earnings",
    title: "Earnings Season",
    dashboard: "src/markets/calendar/components/CalendarDashboard.jsx",
    module: "src/panels/calendar/earnings.jsx",
    placeholders: "calendar:earnings",
  },
  {
    key: "calendar:key-data",
    marketId: "calendar",
    panelId: "key-data",
    title: "Key US Releases",
    dashboard: "src/markets/calendar/components/CalendarDashboard.jsx",
    module: "src/panels/calendar/key-data.jsx",
    placeholders: "calendar:key-data",
  },
  {
    key: "calendar:treasury",
    marketId: "calendar",
    panelId: "treasury",
    title: "Treasury Auctions",
    dashboard: "src/markets/calendar/components/CalendarDashboard.jsx",
    module: "src/panels/calendar/treasury.jsx",
    placeholders: "calendar:treasury",
  },
  {
    key: "calendar:options",
    marketId: "calendar",
    panelId: "options",
    title: "Options Expiry",
    dashboard: "src/markets/calendar/components/CalendarDashboard.jsx",
    module: "src/panels/calendar/options.jsx",
    placeholders: "calendar:options",
  },
  {
    key: "calendar:release-impact",
    marketId: "calendar",
    panelId: "release-impact",
    title: "Release Impact Tracker",
    dashboard: "src/markets/calendar/components/CalendarDashboard.jsx",
    module: "src/panels/calendar/release-impact.jsx",
    placeholders: "calendar:release-impact",
  },
  {
    key: "calendar:catalyst-wall",
    marketId: "calendar",
    panelId: "catalyst-wall",
    title: "Market Catalyst Wall",
    dashboard: "src/markets/calendar/components/CalendarDashboard.jsx",
    module: "src/panels/calendar/catalyst-wall.jsx",
    placeholders: "calendar:catalyst-wall",
  },
  {
    key: "bls:kpi",
    marketId: "bls",
    panelId: "kpi",
    title: "Key Labor Market Indicators",
    dashboard: "src/markets/bls/components/BlsDashboard.jsx",
    module: "src/panels/bls/kpi.jsx",
    placeholders: "bls:kpi",
  },
  {
    key: "bls:trends-top",
    marketId: "bls",
    panelId: "trends-top",
    title: "Trends (3-Year) — Top",
    dashboard: "src/markets/bls/components/BlsDashboard.jsx",
    module: "src/panels/bls/trends-top.jsx",
    placeholders: "bls:trends-top",
  },
  {
    key: "bls:trends-bottom",
    marketId: "bls",
    panelId: "trends-bottom",
    title: "Trends (3-Year) — Bottom",
    dashboard: "src/markets/bls/components/BlsDashboard.jsx",
    module: "src/panels/bls/trends-bottom.jsx",
    placeholders: "bls:trends-bottom",
  },
  {
    key: "bls:jolts",
    marketId: "bls",
    panelId: "jolts",
    title: "JOLTS",
    dashboard: "src/markets/bls/components/BlsDashboard.jsx",
    module: "src/panels/bls/jolts.jsx",
    placeholders: "bls:jolts",
  },
  {
    key: "bls:productivity",
    marketId: "bls",
    panelId: "productivity",
    title: "Productivity",
    dashboard: "src/markets/bls/components/BlsDashboard.jsx",
    module: "src/panels/bls/productivity.jsx",
    placeholders: "bls:productivity",
  },
  {
    key: "bls:cpi-components",
    marketId: "bls",
    panelId: "cpi-components",
    title: "CPI Components",
    dashboard: "src/markets/bls/components/BlsDashboard.jsx",
    module: "src/panels/bls/cpi-components.jsx",
    placeholders: "bls:cpi-components",
  },
  {
    key: "bls:ppi-by-industry",
    marketId: "bls",
    panelId: "ppi-by-industry",
    title: "PPI by Industry",
    dashboard: "src/markets/bls/components/BlsDashboard.jsx",
    module: "src/panels/bls/ppi-by-industry.jsx",
    placeholders: "bls:ppi-by-industry",
  },
  {
    key: "bls:eci",
    marketId: "bls",
    panelId: "eci",
    title: "Employment Cost Index",
    dashboard: "src/markets/bls/components/BlsDashboard.jsx",
    module: "src/panels/bls/eci.jsx",
    placeholders: "bls:eci",
  },
  {
    key: "bls:unemployment-duration",
    marketId: "bls",
    panelId: "unemployment-duration",
    title: "Unemployment Duration",
    dashboard: "src/markets/bls/components/BlsDashboard.jsx",
    module: "src/panels/bls/unemployment-duration.jsx",
    placeholders: "bls:unemployment-duration",
  },
  {
    key: "eia:prices",
    marketId: "eia",
    panelId: "prices",
    title: "US Electricity Retail Prices",
    dashboard: "src/markets/eia/EiaMarket.jsx",
    module: "src/panels/eia/prices.jsx",
    placeholders: "eia:prices",
  },
  {
    key: "eia:consumption",
    marketId: "eia",
    panelId: "consumption",
    title: "Electricity Consumption",
    dashboard: "src/markets/eia/EiaMarket.jsx",
    module: "src/panels/eia/consumption.jsx",
    placeholders: "eia:consumption",
  },
  {
    key: "eia:trends",
    marketId: "eia",
    panelId: "trends",
    title: "Price Trends (3-Year Monthly)",
    dashboard: "src/markets/eia/EiaMarket.jsx",
    module: "src/panels/eia/trends.jsx",
    placeholders: "eia:trends",
  },
  {
    key: "eia:co2",
    marketId: "eia",
    panelId: "co2",
    title: "CO₂ Emissions by Sector (US)",
    dashboard: "src/markets/eia/EiaMarket.jsx",
    module: "src/panels/eia/co2.jsx",
    placeholders: "eia:co2",
  },
  {
    key: "eia:petroleum",
    marketId: "eia",
    panelId: "petroleum",
    title: "Petroleum",
    dashboard: "src/markets/eia/EiaMarket.jsx",
    module: "src/panels/eia/petroleum.jsx",
    placeholders: "eia:petroleum",
  },
  {
    key: "eia:natural-gas",
    marketId: "eia",
    panelId: "natural-gas",
    title: "Natural Gas",
    dashboard: "src/markets/eia/EiaMarket.jsx",
    module: "src/panels/eia/natural-gas.jsx",
    placeholders: "eia:natural-gas",
  },
  {
    key: "alerts:kpi",
    marketId: "alerts",
    panelId: "kpi",
    title: "Alert Status",
    dashboard: "src/markets/alerts/components/AlertsDashboard.jsx",
    module: "src/panels/alerts/kpi.jsx",
    placeholders: "alerts:kpi",
  },
  {
    key: "alerts:active-alerts",
    marketId: "alerts",
    panelId: "active-alerts",
    title: "Active Alerts",
    dashboard: "src/markets/alerts/components/AlertsDashboard.jsx",
    module: "src/panels/alerts/active-alerts.jsx",
    placeholders: "alerts:active-alerts",
  },
  {
    key: "alerts:alert-rules",
    marketId: "alerts",
    panelId: "alert-rules",
    title: "Alert Rules",
    dashboard: "src/markets/alerts/components/AlertsDashboard.jsx",
    module: "src/panels/alerts/alert-rules.jsx",
    placeholders: "alerts:alert-rules",
  },
  {
    key: "watchlist:kpi",
    marketId: "watchlist",
    panelId: "kpi",
    title: "Watchlist Summary",
    dashboard: "src/markets/watchlist/WatchlistMarket.jsx",
    module: "src/panels/watchlist/kpi.jsx",
    placeholders: "watchlist:kpi",
  },
  {
    key: "watchlist:my-tickers",
    marketId: "watchlist",
    panelId: "my-tickers",
    title: "My Tickers",
    dashboard: "src/markets/watchlist/WatchlistMarket.jsx",
    module: "src/panels/watchlist/my-tickers.jsx",
    placeholders: "watchlist:my-tickers",
  },
  {
    key: "watchlist:my-metrics",
    marketId: "watchlist",
    panelId: "my-metrics",
    title: "My Metrics",
    dashboard: "src/markets/watchlist/WatchlistMarket.jsx",
    module: "src/panels/watchlist/my-metrics.jsx",
    placeholders: "watchlist:my-metrics",
  },
  {
    key: "analytics:kpi",
    marketId: "analytics",
    panelId: "kpi",
    title: "Analytics Key Metrics",
    dashboard: "src/markets/analytics/AnalyticsMarket.jsx",
    module: "src/panels/analytics/kpi.jsx",
    placeholders: "analytics:kpi",
  },
  {
    key: "analytics:provenance",
    marketId: "analytics",
    panelId: "provenance",
    title: "Provenance Audit",
    dashboard: "src/markets/analytics/AnalyticsMarket.jsx",
    module: "src/panels/analytics/provenance.jsx",
    placeholders: "analytics:provenance",
  },
  {
    key: "analytics:diagnostics",
    marketId: "analytics",
    panelId: "diagnostics",
    title: "API Health Diagnostics",
    dashboard: "src/markets/analytics/AnalyticsMarket.jsx",
    module: "src/panels/analytics/diagnostics.jsx",
    placeholders: "analytics:diagnostics",
  },
  {
    key: "analytics:server",
    marketId: "analytics",
    panelId: "server",
    title: "Server Info",
    dashboard: "src/markets/analytics/AnalyticsMarket.jsx",
    module: "src/panels/analytics/server.jsx",
    placeholders: "analytics:server",
  },
  {
    key: "analytics:api-usage",
    marketId: "analytics",
    panelId: "api-usage",
    title: "API Usage",
    dashboard: "src/markets/analytics/AnalyticsMarket.jsx",
    module: "src/panels/analytics/api-usage.jsx",
    placeholders: "analytics:api-usage",
  },
  {
    key: "analytics:source-health",
    marketId: "analytics",
    panelId: "source-health",
    title: "Data Source Health",
    dashboard: "src/markets/analytics/AnalyticsMarket.jsx",
    module: "src/panels/analytics/source-health.jsx",
    placeholders: "analytics:source-health",
  },
  {
    key: "analytics:endpoints",
    marketId: "analytics",
    panelId: "endpoints",
    title: "Endpoint Metrics",
    dashboard: "src/markets/analytics/AnalyticsMarket.jsx",
    module: "src/panels/analytics/endpoints.jsx",
    placeholders: "analytics:endpoints",
  },
  {
    key: "analytics:freshness",
    marketId: "analytics",
    panelId: "freshness",
    title: "Data Freshness",
    dashboard: "src/markets/analytics/AnalyticsMarket.jsx",
    module: "src/panels/analytics/freshness.jsx",
    placeholders: "analytics:freshness",
  },
  {
    key: "analytics:error-log",
    marketId: "analytics",
    panelId: "error-log",
    title: "Error Log",
    dashboard: "src/markets/analytics/AnalyticsMarket.jsx",
    module: "src/panels/analytics/error-log.jsx",
    placeholders: "analytics:error-log",
  },
  {
    key: "analytics:mem-cache",
    marketId: "analytics",
    panelId: "mem-cache",
    title: "Memory Cache",
    dashboard: "src/markets/analytics/AnalyticsMarket.jsx",
    module: "src/panels/analytics/mem-cache.jsx",
    placeholders: "analytics:mem-cache",
  },
  {
    key: "analytics:cache-files",
    marketId: "analytics",
    panelId: "cache-files",
    title: "File Cache",
    dashboard: "src/markets/analytics/AnalyticsMarket.jsx",
    module: "src/panels/analytics/cache-files.jsx",
    placeholders: "analytics:cache-files",
  },
  {
    key: "analytics:routes",
    marketId: "analytics",
    panelId: "routes",
    title: "Express Routes",
    dashboard: "src/markets/analytics/AnalyticsMarket.jsx",
    module: "src/panels/analytics/routes.jsx",
    placeholders: "analytics:routes",
  },
  {
    key: "analytics:panel-trace",
    marketId: "analytics",
    panelId: "panel-trace",
    title: "Panel Trace Inspector",
    dashboard: "src/markets/analytics/AnalyticsMarket.jsx",
    module: "src/panels/analytics/panel-trace.jsx",
    placeholders: "analytics:panel-trace",
  },
  {
    key: "analytics:coverage-matrix",
    marketId: "analytics",
    panelId: "coverage-matrix",
    title: "Endpoint Coverage Matrix",
    dashboard: "src/markets/analytics/AnalyticsMarket.jsx",
    module: "src/panels/analytics/coverage-matrix.jsx",
    placeholders: "analytics:coverage-matrix",
  },
];

export function getPanelManifestEntry(marketId, panelId) {
  return PANEL_MANIFEST.find((e) => e.marketId === marketId && e.panelId === panelId) || null;
}

export function listPanelsForMarket(marketId) {
  return PANEL_MANIFEST.filter((e) => e.marketId === marketId);
}
