/**
 * Global panel registry — all markets.
 * Generated by scripts/scaffold-all-market-panels.mjs (bonds pack is hand-maintained).
 */
import { EQUITIES_PANELS } from './equities/index.js';
import { BONDS_PANELS } from './bonds/index.js';
import { FX_PANELS } from './fx/index.js';
import { DERIVATIVES_PANELS } from './derivatives/index.js';
import { REALESTATE_PANELS } from './realEstate/index.js';
import { INSURANCE_PANELS } from './insurance/index.js';
import { COMMODITIES_PANELS } from './commodities/index.js';
import { GLOBALMACRO_PANELS } from './globalMacro/index.js';
import { EQUITIESDEEPDIVE_PANELS } from './equitiesDeepDive/index.js';
import { CRYPTO_PANELS } from './crypto/index.js';
import { CREDIT_PANELS } from './credit/index.js';
import { SENTIMENT_PANELS } from './sentiment/index.js';
import { CALENDAR_PANELS } from './calendar/index.js';
import { BLS_PANELS } from './bls/index.js';
import { EIA_PANELS } from './eia/index.js';
import { ALERTS_PANELS } from './alerts/index.js';
import { WATCHLIST_PANELS } from './watchlist/index.js';
import { ANALYTICS_PANELS } from './analytics/index.js';

const byKey = new Map();
const byMarket = new Map();

function register(panel) {
  if (!panel?.key) return;
  byKey.set(panel.key, panel);
  for (const m of panel.markets || []) {
    if (!byMarket.has(m)) byMarket.set(m, []);
    const list = byMarket.get(m);
    if (!list.find((p) => p.key === panel.key)) list.push(panel);
  }
}

const ALL = [
  ...EQUITIES_PANELS,
  ...BONDS_PANELS,
  ...FX_PANELS,
  ...DERIVATIVES_PANELS,
  ...REALESTATE_PANELS,
  ...INSURANCE_PANELS,
  ...COMMODITIES_PANELS,
  ...GLOBALMACRO_PANELS,
  ...EQUITIESDEEPDIVE_PANELS,
  ...CRYPTO_PANELS,
  ...CREDIT_PANELS,
  ...SENTIMENT_PANELS,
  ...CALENDAR_PANELS,
  ...BLS_PANELS,
  ...EIA_PANELS,
  ...ALERTS_PANELS,
  ...WATCHLIST_PANELS,
  ...ANALYTICS_PANELS
];

for (const p of ALL) register(p);

export function getPanel(key) {
  return byKey.get(key) || null;
}

export function getPanelForMarket(marketId, panelId) {
  return getPanel(`${marketId}:${panelId}`)
    || (byMarket.get(marketId) || []).find((p) => p.panelId === panelId)
    || null;
}

export function listPanelsForMarket(marketId) {
  return byMarket.get(marketId) || [];
}

export function listAllPanels() {
  return [...byKey.values()];
}

export { register as registerPanel };
