// src/hub/markets.config.js
export const MARKETS = [
  { id: 'equities',         label: 'Equities' },
  { id: 'bonds',            label: 'Bonds' },
  { id: 'fx',               label: 'FX' },
  { id: 'derivatives',      label: 'Derivatives' },
  { id: 'realEstate',       label: 'Real Estate' },
  { id: 'insurance',        label: 'Insurance' },
  { id: 'commodities',      label: 'Commodities' },
  { id: 'globalMacro',      label: 'Macro' },
  { id: 'imf',               label: 'IMF' },
  { id: 'worldbank',         label: 'World Bank' },
  { id: 'equitiesDeepDive', label: 'Equity+' },
  { id: 'crypto',           label: 'Crypto' },
  { id: 'credit',           label: 'Credit' },
  { id: 'sentiment',        label: 'Sentiment' },
  { id: 'calendar',         label: 'Calendar' },
  { id: 'bls',              label: 'BLS' },
  { id: 'eia',              label: 'EIA' },
  { id: 'census',           label: 'Census' },
  { id: 'alerts',           label: 'Alerts' },
  { id: 'watchlist',        label: 'Watchlist' },
  { id: 'analytics',        label: 'Analytics' },
];

export const DEFAULT_MARKET = 'equities';

export const SEARCH_INDEX = [
  { marketId: 'equities',         label: 'Equities',    subTabs: ['Heatmap', 'List', 'Portfolio', 'Radar', 'Data Hub'] },
  { marketId: 'bonds',            label: 'Bonds',       subTabs: ['Yield Curve', 'Credit Matrix', 'Spread Monitor', 'Duration Ladder', 'Breakevens'] },
  { marketId: 'fx',               label: 'FX',          subTabs: ['Rate Matrix', 'Carry Map', 'DXY Tracker', 'Top Movers'] },
  { marketId: 'derivatives',      label: 'Derivatives', subTabs: ['Vol Surface', 'VIX Term Structure', 'Options Flow'] },
  { marketId: 'realEstate',       label: 'Real Estate', subTabs: ['Price Index', 'REIT Screen', 'Affordability Map', 'Cap Rate Monitor'] },
  { marketId: 'insurance',        label: 'Insurance',   subTabs: ['Cat Bond Spreads', 'Combined Ratio', 'Reserve Adequacy', 'Reinsurance Pricing'] },
  { marketId: 'commodities',      label: 'Commodities', subTabs: ['Price Dashboard', 'Futures Curve', 'Sector Heatmap', 'Supply & Demand', 'COT Positioning'] },
  { marketId: 'globalMacro',      label: 'Macro',       subTabs: ['Scorecard', 'Growth & Inflation', 'Central Bank Rates', 'Debt Monitor', 'Economic Activity'] },
  { marketId: 'imf',               label: 'IMF',         subTabs: ['Scorecard', 'Growth & Inflation', 'Reserves', 'COFER'] },
  { marketId: 'worldbank',         label: 'World Bank',   subTabs: ['Scorecard', 'Growth Trends', 'Development', 'Trade'] },
  { marketId: 'equitiesDeepDive', label: 'Equity+',     subTabs: ['Sector Rotation', 'Factor Rankings', 'Earnings Watch', 'Short Interest', 'Inst. Holdings'] },
  { marketId: 'crypto',           label: 'Crypto',      subTabs: ['Market Overview', 'Cycle Indicators', 'DeFi & Chains', 'Funding & Positioning'] },
  { marketId: 'credit',           label: 'Credit',      subTabs: ['IG / HY Dashboard', 'EM Bonds', 'Loan Market', 'Default Watch'] },
  { marketId: 'sentiment',        label: 'Sentiment',   subTabs: ['Fear & Greed', 'CFTC Positioning', 'Risk Dashboard', 'Cross-Asset Returns', 'Correlation Matrix'] },
  { marketId: 'calendar',         label: 'Calendar',    subTabs: ['Economic Calendar', 'Central Banks', 'Earnings Season', 'Key Releases'] },
  { marketId: 'bls',              label: 'BLS',          subTabs: ['Labor Market', 'Prices', 'Trends'] },
  { marketId: 'eia',              label: 'EIA',          subTabs: ['Electricity', 'Emissions', 'Energy Overview'] },
  { marketId: 'census',           label: 'Census',       subTabs: ['Housing', 'Trade', 'Retail', 'Durable Goods'] },
  { marketId: 'alerts',           label: 'Alerts',      subTabs: ['Active Alerts', 'Alert Rules'] },
  { marketId: 'watchlist',        label: 'Watchlist',   subTabs: ['My Tickers', 'My Metrics'] },
  { marketId: 'analytics',        label: 'Analytics',   subTabs: ['API Usage', 'Endpoints', 'Data Freshness', 'Rate Limits', 'Cache'] },
];
